export const REQUEST_UNSPLASH_STARTED = "REQUEST_UNSPLASH_STARTED";
export const REQUEST_UNSPLASH_LOADED = "REQUEST_UNSPLASH_LOADED";
export const REQUEST_UNSPLASH_ERROR = "REQUEST_UNSPLASH_ERROR";
export const REQUEST_PHOTO_LIKE = "REQUEST_PHOTO_LIKE";
export const REQUEST_PHOTO_UNLIKE = "REQUEST_PHOTO_UNLIKE";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
